import type { Player } from '@/types/player'

// Mock data for initial development
export const mockPlayers: Player[] = [
  {
    id: '1',
    name: 'Mike Trout',
    team: 'Los Angeles Angels',
    position: 'CF',
    hits: 185,
    homeRuns: 40,
    average: 0.305,
    atBats: 606,
    runs: 110,
    rbi: 104,
  },
  {
    id: '2',
    name: 'Aaron Judge',
    team: 'New York Yankees',
    position: 'RF',
    hits: 177,
    homeRuns: 62,
    average: 0.311,
    atBats: 569,
    runs: 133,
    rbi: 131,
  },
  {
    id: '3',
    name: 'Mookie Betts',
    team: 'Los Angeles Dodgers',
    position: 'RF',
    hits: 175,
    homeRuns: 35,
    average: 0.289,
    atBats: 606,
    runs: 117,
    rbi: 82,
  },
  {
    id: '4',
    name: 'Ronald Acuña Jr.',
    team: 'Atlanta Braves',
    position: 'RF',
    hits: 217,
    homeRuns: 41,
    average: 0.337,
    atBats: 644,
    runs: 149,
    rbi: 106,
  },
  {
    id: '5',
    name: 'Shohei Ohtani',
    team: 'Los Angeles Angels',
    position: 'DH',
    hits: 174,
    homeRuns: 44,
    average: 0.304,
    atBats: 572,
    runs: 102,
    rbi: 95,
  },
]
